<?php

declare(strict_types=1);

namespace Nqphp\Core\Security;

use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Request;

/**
 * Double-submit-cookie CSRF protection.
 *
 * On every request we ensure a `nqphp_csrf` cookie is present; on
 * state-changing requests (POST/PUT/PATCH/DELETE) we require the
 * `X-CSRF-Token` request header to match the cookie value. Both
 * values are random 32-byte hex strings generated by the runtime.
 *
 * Why double-submit and not server-side sessions:
 *   - the framework is deliberately session-free in Phase 2 — we don't
 *     pull in symfony/session just to anchor a CSRF token;
 *   - the cookie must be readable by JavaScript so that the bundled
 *     `csrf()` helper can return it without a server roundtrip;
 *   - double-submit with `SameSite=Lax` + `Secure` (when TLS is on)
 *     defeats the practical CSRF attack surface for first-party
 *     requests without a session backend.
 *
 * This is intentionally minimal — if your feature needs per-user,
 * per-form, or time-bound tokens, swap this manager for one that does.
 */
final class CsrfTokenManager
{
    public const COOKIE_NAME = 'nqphp_csrf';
    public const HEADER_NAME = 'X-CSRF-Token';

    private const STATE_CHANGING_METHODS = ['POST', 'PUT', 'PATCH', 'DELETE'];

    /** @var string|false|null Cached token for the current request (null = not yet computed). */
    private string|false|null $cached = null;

    public function __construct(
        private readonly bool $secure = false,
        private readonly string $sameSite = 'lax',
    ) {
    }

    /**
     * Read the CSRF token from the request cookie, or `null` if absent.
     */
    public function getToken(Request $request): ?string
    {
        if ($this->cached !== null) {
            return $this->cached === false ? null : $this->cached;
        }
        $value = $request->cookies->get(self::COOKIE_NAME);
        $this->cached = (is_string($value) && $value !== '') ? $value : false;
        return $this->cached === false ? null : $this->cached;
    }

    /**
     * Build a `Set-Cookie` header that the response should attach so
     * the browser persists the CSRF token. The cookie is NOT marked
     * HttpOnly because the runtime JS helper has to read it.
     *
     * Callers should attach the returned Cookie to every Response that
     * may be the first time a client touches the framework.
     */
    public function buildCookie(Request $request): Cookie
    {
        $token = $this->getToken($request) ?? bin2hex(random_bytes(32));
        return new Cookie(
            self::COOKIE_NAME,
            $token,
            0,                                  // session cookie
            '/',
            null,
            $this->secure,
            false,                              // HttpOnly = false (JS reads it)
            false,                              // raw
            $this->sameSite,
        );
    }

    /**
     * Verify that a state-changing request carries a valid CSRF token.
     * Returns `true` for safe methods (GET/HEAD/OPTIONS) — those are
     * not state-changing and CSRF does not apply.
     *
     * For state-changing methods, the `X-CSRF-Token` header MUST equal
     * the cookie value. A missing cookie, missing header, or mismatch
     * is treated as a CSRF failure.
     */
    public function isValid(Request $request): bool
    {
        if (!in_array($request->getMethod(), self::STATE_CHANGING_METHODS, true)) {
            return true;
        }
        $cookie = $this->getToken($request);
        if ($cookie === null) {
            return false;
        }
        $header = $request->headers->get(self::HEADER_NAME);
        if (!is_string($header) || $header === '') {
            return false;
        }
        return hash_equals($cookie, $header);
    }

    /**
     * Whether the request method is one we enforce CSRF on.
     */
    public function isStateChanging(Request $request): bool
    {
        return in_array($request->getMethod(), self::STATE_CHANGING_METHODS, true);
    }
}
